[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "space_station"
version = "0.0.1"
description = "Space Station project"
readme = "README.md"
requires-python = ">=3.10"
dynamic = ["dependencies"]

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}

# Исправленный блок: ищем пакеты прямо в корне
[tool.setuptools.packages.find]
where = ["."]
include = ["app*"]

[tool.pytest.ini_options]
minversion = "7.0"
addopts = "--cov=app --cov-report=xml"
testpaths = [
    "tests",
]
pythonpath = ["."]
filterwarnings = [
    "ignore::litestar.exceptions.LitestarDeprecationWarning",
    "ignore:.*was never awaited:RuntimeWarning",
]
